### ISSUE TITLE
Can't make it work with Foundation 5

### ISSUE THREAD

**Issue by jcastro** [mechio/takana#39]
Hello!

This is awesome and just was I was looking for. However, I can't get it to work with Foundation 5 using compass. Is there a way to fix this? Thanks!

**Comment by vulfox** [comment]
Had the same problem.

I also used grunt generator-zf5 which places the zurb foundation inside app/ -folder inside your project folder so you have to remember to cd to my/new/project/APP/ not just my/new/project/ and then use:

takana . -i bower_components/foundation/scss

or..

cd to my/new/project 
and put the app/ folder in the takana command instead:

takana . -i app/bower_components/foundation/scss
