### ISSUE TITLE
Add sass support

### ISSUE THREAD

**Issue by mattma** [mechio/takana#56]
I have tested the sample code which match your video example. It works in SCSS but not in sass. Are you going to make it work in sass as well? thanks.

**Comment by P233** [comment]
I've found a way to make takana work with indented Sass syntax.

After installing takana: 

1. Add `'sass', ` to [takana/lib/server.coffee line 61](https://github.com/mechio/takana/blob/master/lib/server.coffee#L61)

2. Add a new line `sass : scss` underneath [takana/lib/renderer/index.coffee line 8](https://github.com/mechio/takana/blob/master/lib/renderer/index.coffee#L8)

**Comment by mattma** [comment]
@P233 Thanks for the head up. It has been a while that I touched the Takana. Do you have a working example somewhere. very basic that I could download and play with it. I tried to do the same setup that I had before (delete the project folder) but I could not even get the `scss` working with takana. 

I did have latest takana, sublime plugins, browser extension. Do not know where it falls off. Thanks

**Comment by P233** [comment]
Hi @mattma  I can get the latest takana works on Mavericks but not Yosemite, same issues as in #53. Maybe try to downgrade to `0.2.1`?

**Comment by mattma** [comment]
Thanks, That helps. I think Takana should extend their editor support to WebStorm, and others. And also adding more examples to get started. My two cents.

**Comment by barnaby** [comment]
@P233 thanks for your help.

I've just pushed a version `0.4.2`, which supports indented sass.

**Comment by mattma** [comment]
Is there an example that you could add into the repo? so that we could just clone, install the dependency, then simply code in sublime and see the action in chrome? That would be awesome.

**Comment by barnaby** [comment]
@mattma yup, just pushed https://github.com/mechio/takana-example. Let me know how that goes :)

**Comment by mattma** [comment]
I have tested the `takana-example` project. Thank you for doing that. 

I just created a new [issue](https://github.com/mechio/takana-example/issues/1) there
