### ISSUE TITLE
Takana breaks when using :not pseudo-selector

### ISSUE THREAD

**Issue by danielkalen** [mechio/takana#64]
Every time I start writing a :not selector takana breaks and throws an error "Segmentation fault: 11".

I doubt this is an error with libsass because when I refresh takana after adding the :not selector everything keeps working fine as it should.

**Comment by nc** [comment]
@danielkalen thank you for filing this.

I can confirm the crash when an incomplete `:not` is present. For example

```
  body:not('') {

  }
```

Will not result in a segmentation fault, whereas this does:

```
  body:not() {

  }
```

I would suggest filing this as a libsass bug.
