### ISSUE TITLE
Takana proxy or different connect webserver

### ISSUE THREAD

**Issue by krisak** [mechio/takana#65]
Hello, i wasnt able to find it anywhere so i am asking. Stupid question.

Takana works only with static files am i right? Is it possible to use it as proxy or change the webserver takana?

Thank you for your response and work on this cool tool.

**Comment by nc** [comment]
Hey @krisak I'm not sure I fully understand your question but I'll try and answer to the best of my knowledge. If I miss the mark please reply with more information about what exactly you're trying to accomplish. 

Takana works with SCSS files on your filesystem, not ones served via a webserver. So if you're trying to work with SCSS files generated on the fly, that won't work. Or at least, you'll need to modify Takana to suit your needs there.

**Comment by krisak** [comment]
Thank you for your answer :+1: 

Truth is i wasnt looking how its implemented so thats why that dumb question. I am still not sure if i can somehow make it run when developing dynamic pages and it seems wrong to have two instances of preprocessor runing (when you have gulp watching for example).

Its supercool tho. Thanks!

**Comment by nc** [comment]
@krisak glad to hear that. You should remove sass files from your gulpfile watch block when using Takana, you don't need both.
