### ISSUE TITLE
Updating Node-Sass to support Susy & Breakpoint

### ISSUE THREAD

**Issue by JamesJosephFinn** [mechio/takana#79]
Here's the Takana printout:
```
[21:39:28] [WARN] - error rendering /Users/jamesfinn/.takana/scratch//scss/styles.scss : { file: '/Users/jamesfinn/Documents/larrys-site/bower_modules/breakpoint-sass/stylesheets/breakpoint/parsers',
  line: 198,
  message: ' expected \'in\' keyword in @each directive' }
```
So, I un`@import`ed the Breakpoint library, and then it threw the same error for Susy:
```
message: ' expected \'in\' keyword in @each directive' }
```
So, I un`@import`ed Susy as well, and it was back to green lights.

I figure it's the outdated node-sass in takana:
1. Do you think updating node-sass would correct the errors being thrown by Takana?
2. If so, is it even possible?

**Comment by ob7** [comment]
probably would fix if you know how.  I'v ready elsewhere that installing a earlier verison of node will make it work.

**Comment by ob7** [comment]
node version manager: https://github.com/creationix/nvm

**Comment by billybrown** [comment]
+1

I have Takana working using nvm (using node version 0.12.7), but Takana is still using an older version of node-sass (looks like Takana is still at 1.0.1 and the most recent release of node-sass is 3.3.3), so we don't have access to some of the newer libsass features.

**Comment by nc** [comment]
Hey, It's been a while since this was posted. Just wanted to let you know Takana has been updated to the latest node-sass in the latest release. Updating should fix these issues.
