### ISSUE TITLE
Installation fail on Mac

### ISSUE THREAD

**Issue by kelvinkyaw** [mechio/takana#86]
I just typed **sudo npm install -g takana**. But, my mission is failed. Any idea to solve this?

![Uploading Screen Shot 2015-08-23 at 11.04.15 pm.png…]()
![Uploading Screen Shot 2015-08-23 at 11.04.40 pm.png…]()
![Uploading Screen Shot 2015-08-23 at 11.04.52 pm.png…]()

<a href="http://imgbox.com/D69igCYJ" target="_blank"><img src="http://1.t.imgbox.com/D69igCYJ.jpg" alt="image host"/></a> <a href="http://imgbox.com/SQVBBdg4" target="_blank"><img src="http://3.t.imgbox.com/SQVBBdg4.jpg" alt="image host"/></a> <a href="http://imgbox.com/MHyVrLq4" target="_blank"><img src="http://6.t.imgbox.com/MHyVrLq4.jpg" alt="image host"/></a>

**Comment by Romainpetit** [comment]
Getting the exact same error here, I would love to get some help. 
Npm & node latest versions.

**Comment by kelvinkyaw** [comment]
Hay Romain,
