### ISSUE TITLE
Support for Ruby Sass?

### ISSUE THREAD

**Issue by dubstrike** [mechio/takana#88]
I'm working on a Ruby on Rails project and would love to use Takana to speed up development.
Any plans for supporting Ruby Sass or is it just too slow?

Thanks!

**Comment by nc** [comment]
@dubstrike sorry for the super late reply... Ruby Sass is indeed too slow. On large projects a single compile can take upwards of 10 seconds, which renders live-update useless. The threshold for a great live-update experience is ~300ms mark.
